apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: metabase-secret
  namespace: default
data:
  metabase-db-dbname: U3VwZXJTZWNyZXQ=
  metabase-db-port: U3VwZXJTZWNyZXQ=
  metabase-db-user: U3VwZXJTZWNyZXQ=
  metabase-db-pass: U3VwZXJTZWNyZXQ=
  metabase-db-host: U3VwZXJTZWNyZXQ=
