apiVersion: v1
kind: Service
metadata:
  name: metabase-service
  namespace: default
  labels:
    app: metabase
spec:
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31000
  selector:
    app: metabase
  type: NodePort
