# Run kubctl apply (https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#apply)
# kubectl apply -f https://k8s.io/examples/application/deployment.yaml
apiVersion: apps/v1 # required (version of the Kubernetes API)
kind: Deployment # required (kind of object to create)
metadata: # required (Data to uniquely identify the object)
  name: nginx-deployment
  # Options: name, UID, namespace
spec: # required (state for the object, is different for every Kubernetes object)
  selector:
    matchLabels:
      app: nginx
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80