apiVersion: v1
kind: Service
metadata:
  name: keycloak-service
  namespace: default
  labels:
    app: keycloak
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30150
  selector:
    app: keycloak
  type: NodePort
