apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: keycloak
  replicas: 1
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: bitnami/keycloak:21.1.1
          imagePullPolicy: IfNotPresent
          env:
            - name: KEYCLOAK_DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: keycloak-configmap
                  key: keycloak-postgres-host
            - name: KEYCLOAK_DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: keycloak-configmap
                  key: keycloak-postgres-port
            - name: KEYCLOAK_DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: keycloak-configmap
                  key: keycloak-postgres-db
            - name: KEYCLOAK_DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: keycloak-postgres-user
            - name: KEYCLOAK_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: keycloak-postgres-password
            - name: KEYCLOAK_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: keycloak-admin-user
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: keycloak-admin-password
            - name: KEYCLOAK_MANAGEMENT_USER
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: keycloak-management-user
            - name: KEYCLOAK_MANAGEMENT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: keycloak-management-password
