apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
  namespace: default
  labels:
    app: pgadmin
spec:
  ports:
    - protocol: TCP
      port: 3080
      targetPort: 80
      nodePort: 30080
  selector:
    app: pgadmin
  type: NodePort
