kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: home-assistant-config-pv-claim
  namespace: default
  labels:
    app: home-assistant
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
