kind: PersistentVolume
apiVersion: v1
metadata:
  name: home-assistant-config-pv-volume
  namespace: home-assistant
  labels:
    type: local
    app: home-assistant
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home-assistant/config"
