apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-config-pv-claim
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 31Gi
