apiVersion: v1
kind: Service
metadata:
  name: librespeed-service
  namespace: default
  labels:
    app: librespeed
spec:
  selector:
    app: librespeed
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30130
