apiVersion: apps/v1
kind: Deployment
metadata:
  name: librespeed-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: librespeed
  replicas: 1
  template:
    metadata:
      labels:
        app: librespeed
    spec:
      containers:
        - name: librespeed
          image: linuxserver/librespeed:5.3.0
          imagePullPolicy: IfNotPresent
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Europe/Madrid"
          volumeMounts:
            - name: librespeed-volume
              mountPath: /config
      volumes:
        - name: librespeed-volume
          hostPath:
            path: /librespeed
            type: Directory
