apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-password
---
apiVersion: v1
kind: Service # Created to allow communication with mongodb
metadata:
  name: mongodb-service
spec:
  selector: # Used to indicate which pod should be used for connection
    app: mongodb
  # default type is ClusterIP (internal service, gives an internal IP addr)
  ports:
    - protocol: TCP
      port: 27017 # Exposed service port
      targetPort: 27017 # Pod port
 