apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: default
  labels:
    app: minio
type: Opaque
data:
    minio-root-username: cm9vdA==
    minio-root-password: bXlwYXNzd29yZA==
