kind: PersistentVolume
apiVersion: v1
metadata:
  name: minio-pv-volume
  namespace: default
  labels:
    type: local
    app: minio
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/minio/data"
