apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: default
  labels:
    app: minio
spec:
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: 30100
    - protocol: TCP
      port: 9001
      targetPort: 9001
      nodePort: 30101
  selector:
    app: minio
  type: NodePort
