apiVersion: v1
kind: Service
metadata:
  name: redisinsight-service
  namespace: default
  labels:
    app: redisinsight
spec:
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
      nodePort: 30070
  selector:
    app: redisinsight
  type: NodePort
