apiVersion: apps/v1
kind: Deployment
metadata:
  name: redisinsight-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redisinsight
  template:
    metadata:
      labels:
        app: redisinsight
    spec:
      containers:
        - name: redisinsight
          image: redislabs/redisinsight:1.14.0
          imagePullPolicy: IfNotPresent
