apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: default
  labels:
    app: postgres
spec:
  ports:
    - name: postgres
      port: 5432
      nodePort: 5432
  type: NodePort
  selector:
    app: postgres
