kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-volume
  namespace: default
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/postgres/data"
